apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: poseidon
spec:
  interval: 120m
  releaseName: rabbitmq
  chart:
    spec:
      chart: rabbitmq
      version: "8.26.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    replicaCount: 1
    ingress:
      enabled: false
      ingressClassName: nginx
      hostname: rabbit.127-0-0-1.nip.io
    persistence:
      storageClass: nfs-csi
      enabled: false
      size: 2Gi
