apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: brokers
spec:
  interval: 5m
  releaseName: emqx
  chart:
    spec:
      chart: emqx
      version: '4.2.x'
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  values:
    persistence:
      enable: true
    emqxConfig:
      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqw_management,emqx_dashboard,emqx_statsd"
