apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: triton
  namespace: flux-system
spec:
  interval: 1440m
  ref:
    branch: develop
  url: https://github.com/AlexisMtr/Triton
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: sqlserver
  namespace: flux-system
spec:
  ref:
    branch: master
  url: https://github.com/AlexisMtr/mssql-docker
  interval: 1440m
