apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dapr
  namespace: dapr-system
spec:
  interval: 5m
  releaseName: dapr
  chart:
    spec:
      chart: dapr
      version: ">=1.0.0"
      sourceRef:
        kind: HelmRepository
        name: dapr
        namespace: flux-system
