auth:
    username: ENC[AES256_GCM,data:WIa44qJ9,iv:watT8nsycOD1/MPEBZ3Ob+hDrADKW9CMz3VtkdLabvE=,tag:415b8ptjdl6VHI0l+npcnw==,type:str]
    password: ENC[AES256_GCM,data:emnCDuwzaW4xTE4Ha4j5ppV7bkk=,iv:pR3ylEHX0ieEnSt/4NTaGFbINvQM5DKk6g0rR8+ZusY=,tag:8GQuAvo4RI05ZjXYufqs7g==,type:str]
    erlangCookie: ENC[AES256_GCM,data:I4uiGfXP1SjxKse2215NiIbbMLNCVswdrJYbmQqY6FVbByq52vx9CwAoy9c=,iv:btAlfqo3d2IlSPcxoFQuhuSYkY6MFfkYZahQMnfncH4=,tag:3OWQv1WGirKqO0g+yg3n+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2022-06-08T15:08:58Z'
    mac: ENC[AES256_GCM,data:QS7U/4MyJMe03VdkeT0r/Ra/poqMEJRbhc6VGd/bdRTInpzvbFoXb4OiGCLTpyQFxwO/Pf6XbzHvnvS4jYNgWagI7yWSUrHz1Wu90+vNDCImEoej/kQRYSIvxb8rslMB/tERLrLvjrvYEY7HkThQ646lEybsVq0acVV7xLscWmI=,iv:JPCLV4N9vkDfEuSQjadJmqnLUo7yJg1zfwiQbfQTRxw=,tag:obixorA8fg8NZQESBq3xfA==,type:str]
    pgp:
    -   created_at: '2022-06-08T15:08:57Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzS5tEvtII6KARAAs7jFuN7Dfnn0Uu+085g0xOdTotqDk+AbBopbiyfr15c6
            zydBZebEKsu+1xnpAmnXEOjPrM++9buZIVLy4Eqyj81FGGLUsLb9HYqTtoJYMFH4
            Q6sqB/4/heCJ1vx1gxsNYSZJl9/COkMoY44HeSXhrWyH5M76fVR554+aRseXMoux
            IBL3qXQN0GlZMImakLgoZPQlmUr54qAjL9zUL0zQ1UsSNwlmanfbL6JEd2i8VRPu
            AugdFaNguS0IyAQj7k5K3WU+5D3PpD3TyrccChG6sh+vysR0FvypPk2Cka8F36RW
            /v0CEqa0M9e821d9Pf19HTlpM1BSk5+7sAueX0BS8fpuQlGcVGNMIrUaDYW5oRxM
            fFzFPng19NzwuDmnRauW5kAuFmKmaDfI9IUt4pNPBjTbilqOwNmMBJaL6RhEU10s
            XsXUEpaVMj1IBPJnzX+7nsf/p6FuvyTNgdtgYHUCBHZwWwa8AZ1ngQQhh6b9H9pO
            OLM2/j5iM/1CFhlMn1pABeeU6laogpA9mDt4vQEngHq+Le0OUxUxcC2Z0zxRYxH/
            30zUGok4bZi8zAJ99grwaW9RH55WbgwegKFLgLAtJjofyReaFPTi9CfhiOC23dxX
            YKH0H3J43Qw9bNSBYIyG+Q91B1yBTHZ8bhosDK6rFgnkAh5xuX0UAYM5w1+US5HS
            XgG3DxsSq6dlaGXUcryScRmxrGV1n3LNV0s86Lwb0skfuD8RtsVpkITrnS0DsnlJ
            bQu/eKp3Q5wnNSy3VJmnG+v3JSks6jC7tZUNWegYJqDzEXuFZbKWbdk0YEMaCnU=
            =KGAM
            -----END PGP MESSAGE-----
        fp: 70ACDC72D77E8C11B2703D7F681B5A1867E2AF78
    unencrypted_suffix: _unencrypted
    version: 3.6.1
