apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: poseidon
spec:
  valuesFrom:
    - kind: Secret
      name: rabbit-secrets-release-values
      valuesKey: values.yaml
      optional: false
