apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    tenant: multi
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: poseidon
---
apiVersion: v1
kind: Namespace
metadata:
  name: dapr-system
---

