apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: amphitrite
  namespace: poseidon
spec:
  values:
    env: development
  valuesFrom:
    - kind: Secret
      name: amphitrite-secrets-release-values
      valuesKey: values.yaml
      optional: false