environment:
    dbConnectionString: ENC[AES256_GCM,data:yVrTV6VLUMmp+LzAewL0upiP2EozxSXRaL+2HlGuOU7g/6lTMUbtTQYlHy/sNcuC839fEe8bkJ+/6Qygm0izORiWek+JjSmwcF84IiXZ3duFthmvBLWmkhSaLPEOVAEZ/mGjskIp7wwTXg8tEY7r52H6B3pNO/3lnpcp55oz1DJlJgV2945wxjvgX5e5Yjy0aov02Erl+9sejYThcijV9qYixuJDLLTm16OA7BIrbvTmEp3MhI5U5D5pN+si263kWqsCiq7zCSV3uMEna1ngw/pDjDVaMlsgCAkjg5q+JDnObQ97jK6bGq5bWuZjzVoQN/fleg1IgubFHDQPvRyTctpHUhA=,iv:B5dXIT9elFYpjsbNg/TGffjva3zSocPH3RNFvfJYzYg=,tag:Oi57u8weiRvWWQe54l4s6A==,type:str]
    issuerKey: ENC[AES256_GCM,data:MkHmDFYYRdi40tvpWNjhpmpwHw==,iv:AVSi2J7iXwzR/mxjBAJO1kSfBe7pxyX3urE4we9p4KI=,tag:O+alzkgi+koNL2EQ2vHM3g==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-07-02T12:44:25Z'
    mac: ENC[AES256_GCM,data:ahUbZWFM83C/rJQ95STLfsLXw9aTHcuKgbDS+MBU1I3H3eTvuXAqDg3on4rcMoHOym3KwQG+iu76GkFk01ciXKb2jmLfBMXZziYNcOg/cYSRsRaTD28FhEU1bztX/tNeBpHV6VJbQEourTNnqXjdFCpbRe9AYAz+TcWNoq3C4AE=,iv:E89RCahI5Yp9nPczBhIG7q96bA8EeombD2z1Ul4Cjz0=,tag:EnAM1jIswuw/fbAdW3N7wQ==,type:str]
    pgp:
    -   created_at: '2021-07-02T12:44:25Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzS5tEvtII6KAQ/9G7z4tZeoipp4eHAr7fsR3PnQJE6jmyyPeJ5OkUVPOR+U
            vO/kILFoxYl/WhYsmum+J3VulHDm8Iieg1qI8VFkpZM7dzGWB7ExtqbKMd00//k3
            /5uCx5sxHnZaEVJDDH/6Ze23oUdcDl7AbUIu/Kr/L+Vr3gkzpHnGMHNg1emh7vdm
            kCJSmIIAPf8/6beoDtoPUKa+7LT1hTO3wQDEut8T2bTifvuHnNU1M3YO+m5bc3O9
            GB/MzIDakQ07OZLiK5rCePX+7N6dWyocJEl8uAGowUqaq27dg9j3RHF3SMg/70N8
            6ucaSOQASBhfKsSl6apiylTcuiPEKa6kMu+qmxHpNm3yjN5gsCbTBltLtGAon+bl
            rNk/cEreyqqrZrYP9N/RwZR61HsIPcwvVVoMJYMG14H1COWOkVb5f9qDRshazhX9
            xVAoITtYncnwT0zUeesFkjnDgGyh7xmA4tV+MGgAWA7qHrZo3tPBrf+v3jCW0OmT
            MIgsFlTNgdHDWP9G9icA8Ukp6c04A84fElsuDkb6aYHDlSETuRKiREoqx8F5R/xP
            1f62TU5JkWAtzkg6/fn5FCjNurwGJC/wDmh/b68uChRIRGLbYs9+0CfYlR8m17oi
            JQH0Ez6hU3o36zG9GFSdvl/7fECifO79zQNwXsAbWwIE2Rvr+jssJMZq5Fy1MKvS
            XAF4gRgcUE/9SELnf3PHmAKtZghnEXLehA/3KBO8lqs0Gk/Uo+8punP649S8mtwr
            WSPz+QKVStG2gbvo+Ezy6FZ+7yMltoUzq1zQ7CnEklsB0VaSMCcz4eR0wjnA
            =n22U
            -----END PGP MESSAGE-----
        fp: 70ACDC72D77E8C11B2703D7F681B5A1867E2AF78
    unencrypted_suffix: _unencrypted
    version: 3.6.1
