kafka:
    username: ""
    password: ENC[AES256_GCM,data:q2RDCpHGMApNH9HlHTrX/vO80gDprNIiBQJyo+NzqaqatijCtjPptH2fcWCmSlu+mxFpFQx+7A32ipVtcVerVrVtUDveTaLmtOWrVga2B/xYzHLqlSOg2D0wm096CP9z5kahm7SVWjSg6wmtJZkV1Bn+Nf+yorUnLBP6IBKzUCL1Onl2WemYnaTpZI/Fc2rea+pwhI/tEk2SMPmXZQ==,iv:AGdlFNoT+h8VD1TTFlSc/lzsTW997V2mUxoGCfv/PxQ=,tag:EJZy1fD1WbuvABDsGebbng==,type:str]
kafa:
    server: ENC[AES256_GCM,data:/XJI2k4cd+93pmSHF9VF+ntN5RGrhWj3Y36+amLW2FqriVc=,iv:i3fK/PhxZ/C3AmbJ9gCYohEdAF0SWC1opO0AovESOB0=,tag:FMS46RODk5iq4w6FxE4mqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-07-09T19:09:12Z'
    mac: ENC[AES256_GCM,data:w1RfGVIAxI07vhOdQF2bk0G/bk+dJ/C/1G2G4OudIu+wcT1dI+PsWSsk56Q9UElmNYhcAFFOGPbQ6eTpwIl0C7cls2TVeoaNvsEJ5OtF9PtgOZ3CZ+qZ4YcAchMHrTAfR83VaWd0KvZmoNjLEreLWJhrxhZiC9O4Fcm9JQDYLQs=,iv:HiPSEWb9egz3mith3Cy2AwDxvO2pbjxFeFZB6pSpkpo=,tag:9/EJegY0V5x8z0bjyEK/wA==,type:str]
    pgp:
    -   created_at: '2021-07-09T19:01:58Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzS5tEvtII6KAQ/9EQfPIsQya/rz/kpkFQvrEtGZANYujDOU2gd+HGkofxjj
            bs8S8FsI6rMb0GLwKVifO9/rx1EgnjgaWOMmsf7IsRd2j3Y7ovN/ir0adAdspO5D
            jzGCbUnnhPs1czkFftVm6Fhabr8++dq+BtpTQDR10KW8LNyQjMWbBusNkHkDH+iX
            Nm6mGvVrsGUXSUSDnJrLJGqdOCp+iBxUuHsiFiWBeke0VFAUyy/deXu5dS12fqGK
            afr6sGsLbX0uJQ6Gghj0w4E2zCoMnu08YDf+eeBbMiinzhfmSJQ8MfyQVXr+ATQ9
            qBIZ6vH4PmCTMG/itgNRvJPFbe8hjRngplOLeE/pqggRvLCCt/uaNLp2VV3jzj0p
            BRpciWnSjapDdUOMK+4RrPRnt9UlyrRjgzaOTPjQlC8j/vAyqz7ur7nZdrCoqbxR
            h2H3SIvNlwofpvCQqBSWQJKmkmLseq0Y4CYCxGAb4J6vWR/AE/VC7j48fIaFumJh
            axgKrPXALz3QUddB9C8f6Sfr8+EQ4ezKwarbkhvRAiq3d1qDa4+NJ2YGtzxD78L5
            4eG0cujByoJzpJuHmFbvymwtudqp2FWJsbl48XEJO3B+OLWQuwnGkLx6M5rxOaMA
            aC22+imPJLfQ+fBTBrXtrkpBS49a9x23wkbdjbZE0mxzXFSfk1IdGIAal5WDmTjS
            XgHjsebRBkoKb2Zifcz1WDZUWX3IjsY653+2oK3+GXyoC8lEZwY0aAv6Oc0sc0yk
            Oe26hyuOlKYHcieBvla21fYUmBV5i/vM9I/UB1Ae425fb7BRzRhIH28SHj49QbE=
            =IVrV
            -----END PGP MESSAGE-----
        fp: 70ACDC72D77E8C11B2703D7F681B5A1867E2AF78
    unencrypted_suffix: _unencrypted
    version: 3.6.1
