apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: athena
  namespace: poseidon
spec:
  values:
    environments:
      environment: Development
      eventPublishTopic: telemetries_back
      eventSubscribeTopic: telemetries
  valuesFrom:
    - kind: Secret
      name: athena-secrets-release-values
      valuesKey: values.yaml
      optional: false