apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
secretGenerator:
- name: amphitrite-secrets-release-values
  files:
  - values.yaml=amphitrite.secrets.yaml
  namespace: poseidon
- name: athena-secrets-release-values
  files:
  - values.yaml=athena.secrets.yaml
  namespace: poseidon
patchesStrategicMerge:
- amphitrite.patch.yaml
- angelie.patch.yaml
- athena.patch.yaml
configurations:
- kustomizeconfig.yaml