apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: triton
  namespace: poseidon
spec:
  valuesFrom:
    - kind: Secret
      name: triton-secrets-release-values
      valuesKey: values.yaml
      optional: false
