apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: ingress
spec:
  interval: 5m
  releaseName: ingress-controller
  chart:
    spec:
      chart: nginx
      version: '>=3.0.0'
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
  values:
    controller:
      updateStrategy:
        rollingUpdate:
          maxUnavailable: 1
        type: RollingUpdate
      replicaCount: 3
      minAvailable: 1
    metrics:
      enabled: true
      serviceMonitor: true
      prometheusRule: true