apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poseidon
  namespace: argocd
spec:
  project: poseidon
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/AlexisMtr/poseidon-gitops.git
    targetRevision: argocd
    path: k8s/argocd/app/development
