apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
patches:
  - path: application-ns.patch.yaml
    target:
      kind: Application
      group: argoproj.io
      version: v1alpha1
