apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: '>=1.0.0'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    cert-manager:
      installCRDs: true