apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: amphitrite
  namespace: poseidon
spec:
  interval: 5m
  releaseName: amphitrite
  chart:
    spec:
      chart: amphitrite
      version: '>=1.0.0'
      sourceRef:
        kind: HelmRepository
        name: poseidon
        namespace: flux-system
  values:
    existingEnvSecret: amphitrite-my-secrets
    env: development

