apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: amphitrite
  namespace: poseidon
spec:
  interval: 5m
  releaseName: amphitrite
  chart:
    spec:
      chart: amphitrite
      version: "2.0.x"
      sourceRef:
        kind: HelmRepository
        name: poseidon
        namespace: flux-system
  values:
    env: development
