apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: angelie
  namespace: poseidon
spec:
  interval: 5m
  releaseName: angelie
  chart:
    spec:
      chart: angelie
      version: "2.0.x"
      sourceRef:
        kind: HelmRepository
        name: poseidon
        namespace: flux-system
  values:
    replicaCount: 1
    dapr:
      enabled: true
    configuration:
      subscribe:
        topic:
          shared: true
          group: angelie_device
          name: devices/+/telemetry
          regex: devices/(.*)/telemetry
        dapr:
          enabled: false
        broker:
          server: emqx-headless.poseidon.svc.cluster.local
          port: 1883
      publish:
        topic: telemetry
        dapr:
          enabled: true
          componentName: rabbitmq-pubsub
