apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: angelie
  namespace: poseidon
spec:
  interval: 5m
  releaseName: angelie
  chart:
    spec:
      chart: angelie
      version: '>=1.0.0'
      sourceRef:
        kind: HelmRepository
        name: poseidon
        namespace: flux-system