apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: athena
  namespace: poseidon
spec:
  interval: 5m
  releaseName: athena
  chart:
    spec:
      chart: athena
      version: '>=1.0.0'
      sourceRef:
        kind: HelmRepository
        name: poseidon
        namespace: flux-system
  values:
    environments:
      faRuntime: dotnet
      faExtensionVersion: ~3