apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: athena
  namespace: poseidon
spec:
  interval: 5m
  releaseName: athena
  chart:
    spec:
      chart: athena
      version: "2.0.x"
      sourceRef:
        kind: HelmRepository
        name: poseidon
        namespace: flux-system
  values:
    configuration:
      azFunction:
        functions:
          DaprEvent:
            disabled: false
      pubSub:
        topics:
          publish: back
          subscribe: telemetry
        dapr:
          pubComponentName: rabbitmq-pubsub
          subComponentName: rabbitmq-pubsub
    dapr:
      enabled: true
      app:
        port: 3001
