apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: triton
  namespace: poseidon
spec:
  interval: 5m
  releaseName: triton
  chart:
    spec:
      chart: helm/triton
      version: "0.1.1"
      sourceRef:
        kind: GitRepository
        name: triton
        namespace: flux-system
  values:
    image:
      tag: 0.1.2-env
    api:
      url: http://amphitrite.127-0-0-1.nip.io/api
    ingress:
      enabled: true
      ingressClassName: public
      hosts:
        - host: triton.127-0-0-1.nip.io
          paths:
            path: /
